### ISSUE TITLE
FeatherCoin issue

### ISSUE THREAD

**Issue by coinwall** [bitcoin-abe/bitcoin-abe#105]
Opened /home/adbeloader/.feathercoin/blocks/blk00000.dat
Exception at 8
Failed to catch up {'blkfile_offset': 0, 'blkfile_number': 100000, 'chain_id': 22, 'loader': None, 'conf': u'feathercoin.conf', 'dirname': u'/home/adbeloader/.feathercoin', 'id': 72L}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Abe/DataStore.py", line 2507, in catch_up
    store.catch_up_dir(dircfg)
  File "/usr/local/lib/python2.7/dist-packages/Abe/DataStore.py", line 2773, in catch_up_dir
    store.import_blkdat(dircfg, ds, blkfile['name'])
  File "/usr/local/lib/python2.7/dist-packages/Abe/DataStore.py", line 2894, in import_blkdat
    if not store.offer_existing_block(hash, chain.id):
  File "/usr/local/lib/python2.7/dist-packages/Abe/DataStore.py", line 2389, in offer_existing_block
    store.offer_block_to_chains(b, frozenset([chain_id]))
  File "/usr/local/lib/python2.7/dist-packages/Abe/DataStore.py", line 2271, in offer_block_to_chains
    b['top'] = store.adopt_orphans(b, 0, chain_ids, chain_ids)
  File "/usr/local/lib/python2.7/dist-packages/Abe/DataStore.py", line 1291, in adopt_orphans
    stack.pop()()
  File "/usr/local/lib/python2.7/dist-packages/Abe/DataStore.py", line 1296, in doit
    store._adopt_orphans_1(stack)
  File "/usr/local/lib/python2.7/dist-packages/Abe/DataStore.py", line 1407, in _adopt_orphans_1
    store._populate_block_txin(int(next_id))
  File "/usr/local/lib/python2.7/dist-packages/Abe/DataStore.py", line 1240, in _populate_block_txin
    (block_id, txin_id, oblock_id))
  File "/usr/local/lib/python2.7/dist-packages/Abe/DataStore.py", line 249, in sql
    store._sql.sql(stmt, params)
  File "/usr/local/lib/python2.7/dist-packages/Abe/SqlAbstraction.py", line 458, in sql
    sql._execute(cached, params)
  File "/usr/local/lib/python2.7/dist-packages/Abe/SqlAbstraction.py", line 439, in _execute
    sql.cursor().execute(stmt, params)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
IntegrityError: (1062, "Duplicate entry '1617197-10493495' for key 'PRIMARY'")

My config:

datadir += [{
       "dirname": "/home/adbeloader/.feathercoin",
       "chain": "FeatherCoin", 
       "code3": "FTC",
       "loader" : "blkfile",
        "conf": "feathercoin.conf" }]

Any suggestions for fix ?

Cheers

**Comment by codethejason** [comment]
I am getting the same error on a different coin. Did you ever resolve this @coinwall ?

**Comment by wrapperband** [comment]
Someone did get Abe running for Feathercoin, might be worth asking on the Feathercoin forum how the issues were fixed. 
http://forum.feathercoin.com/
Post in Newbies to introduce.
