### ISSUE TITLE
UTF-8 warnings?

### ISSUE THREAD

**Issue by zontreck** [bitcoin-abe/bitcoin-abe#192]
commit
Abe/SqlAbstraction.py:440: Warning: Invalid utf8 character string: 'B7C0BD'
  sql.cursor().execute(stmt, params)
Abe/SqlAbstraction.py:440: Warning: Invalid utf8 character string: 'B5989A'
  sql.cursor().execute(stmt, params)
Abe/SqlAbstraction.py:440: Warning: Invalid utf8 character string: 'F4FDCA'
  sql.cursor().execute(stmt, params)
Abe/SqlAbstraction.py:440: Warning: Invalid utf8 character string: 'B6F2CE'
  sql.cursor().execute(stmt, params)
block_tx 339 346

This happens for every block TX. This may however be an issue with MySQL, but it's worth noting. Also, i cannot use loader:RPC, i must use loader:blkfile otherwise ABE refuses to start up at all.

Assistance would be appreciated.

**Comment by dermoth** [comment]
Can you please provide:

1. Your MySQL version and table *engine* ? i.e. the engine shown in
`SHOW TABLE STATUS [...];` or `SHOW CREATE TABLE tablename` from any abe
table.

2. Output of:

    SELECT * FROM configvar;


Note that you should probably be using latest Abe master branch; no
release have been cut out in a while and I don't think even the latest
release will be properly supported.

Regards,

--
Thomas

**Comment by zontreck** [comment]
MySQL 5.7.9, I'll get the rest of the information when I have access to the database. It was complaining a lot about the column length too, had to edit Abe/DataStore.py to make it get past that error. I'll provide the rest of the info in a moment.

**Comment by zontreck** [comment]
show create table configvar: | configvar | CREATE TABLE `configvar` (
  `configvar_name` varchar(100) NOT NULL,
  `configvar_value` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`configvar_name`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 |


Select * from configvar: 
+---------------------------+-----------------+
| configvar_name            | configvar_value |
+---------------------------+-----------------+
| keep_scriptsig            | true            |
| schema_version            | Abe39           |
| sql.binary_type           | binary          |
| sql.clob_type             | LONGTEXT        |
| sql.create_table_epilogue |                 |
| sql.ddl_implicit_commit   | true            |
| sql.int_type              | int             |
| sql.limit_style           | native          |
| sql.max_precision         |                 |
| sql.max_varchar           | 32765           |
| sql.sequence_type         | mysql           |
| use_firstbits             | false           |
+---------------------------+-----------------+

This one loaded by blkfile. I'll load it over again with RPC and paste the error that occurs.

Traceback (most recent call last):
  File "Abe/DataStore.py", line 2519, in catch_up
    if not store.catch_up_rpc(dircfg):
  File "Abe/DataStore.py", line 2591, in catch_up_rpc
    LIMIT 1""", (chain.id,))
TypeError: 'NoneType' object is not iterable

**Comment by zontreck** [comment]
I changed the default charset as well to test this and:
'configvar', 'CREATE TABLE `configvar` (\n  `configvar_name` varchar(100) NOT NULL,\n  `configvar_value` varchar(255) DEFAULT NULL,\n  PRIMARY KEY (`configvar_name`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8'


no changes however, it still throws off the UTF-8 warnings when starting and loading the block file. However, RPC still does not work.

**Comment by dermoth** [comment]
I think the warnings could be ignored, but I'm not sure how I can silence them. Maybe this version of MySQL decided to be "smart" and warn when it think users may be inserting utf8 text into non-utf8 fields, though for binary types it's ridiculous... Being that MySQL is now developed by Oracle behind closed doors I wouldn't be too surprised anyway. Or course, when someone submitted a bug about it (https://bugs.mysql.com/bug.php?id=78851) they classified it as programmer error and offered paid support. Way to go Oracle!

Anyway, the first place I'd look is in the changelogs of v5.6 and v5.7 if there's anything about handling of utf-8 data. Hopefully they'll be as throughout as in the MySQL AB and Sun Microsystems's time...

Maybe try to reproduce it with this simple program, then we can look at ways to prevent it. I don't really have time to install yet another MySQL server but if I do I'd like to know if I can rely on a much simpler script for testing. Right now I'm having no issue with these two:

* MySQL 5.5.46, Debian's build for Jessie
* MariaDB 5.5.40-tokudb-7.5.3-linux-x86_64 (Toku's build, engine is TokuDB on this one)

```python
#!/usr/bin/env python

import MySQLdb

db = MySQLdb.connect(user='abe', db='test')
c = db.cursor()

c.execute('DROP TABLE IF EXISTS bintest')
c.execute('CREATE TABLE bintest (t BINARY(3) PRIMARY KEY) ENGINE=Innodb')

blst = ('B7C0BD'.decode('hex'),
        'B5989A'.decode('hex'),
        'F4FDCA'.decode('hex'),
        'B6F2CE'.decode('hex'))

for val in blst:
    c.execute('INSERT INTO bintest (t) VALUES (%s)', (val,))

c.execute('COMMIT')

c.execute('SELECT t FROM bintest')
for val in c.fetchall():
    print "val:", val[0].encode('hex')

c.execute('DROP TABLE IF EXISTS bintest')
```

Regarding the rpc issue, I'm not surprised. I've seen that same error all over: assuming an empty set will return an empty iterable. At least with MySQLdb it's not the case; Is this from latest Abe code? I though I fixed something like this recently, but it could be for a different database (postgres or sqlite). I'll have a quick look.

Thanks

**Comment by dermoth** [comment]
Actually rpc issue is fixed in 0b7f1e7 already; I came across is while testing other changes.

It's part of PR #189 which I'm still testing...

**Comment by zontreck** [comment]
Wouldnt totally make sense. I did also try a utf8 charset. Same warnings

**Comment by zontreck** [comment]
I will install an older 5.6 or below server to see if i get those warnings. Though i do like the new simplicity of installing a brand new data directory in 5.7.9.   " Mysqld --initalize "




Anyway ill find the older servers in the mysql repository and build it, seems they dont include the install db binary in the tar archive for mac. Have to build from source to get that program

**Comment by zontreck** [comment]
I can test for sure. I've actually had to begin redownloading the entire blockchain since the hard drive the chain was stored on randomly decided to stop working... So i figured this is the perfect time to rebuild my ABE blockchain database as well since it can simply catch up at the same time bitcoin downloads it's data.   

Anyhow. MySQL 5.6 also seems to be throwing the UTF-8 errors... checking the charset and switching if necessary.  I'm on the latest commit on the master branch BTW.

**Comment by zontreck** [comment]
Same issue on "Server version: 5.5.46 MySQL Community Server (GPL)"

Constant UTF-8 warnings. Database is utf-8 charset.

**Comment by zontreck** [comment]
The program you gave me above produced the same issues of UTF8 warnings

**Comment by wodin** [comment]
See this https://bugs.mysql.com/bug.php?id=79317

**Comment by dermoth** [comment]
Copying my comment from the referenced commit:

I hardly think [ `_binary` prefix ] will be supported by other databases. I really don't like the idea of having to explicitly pass binary data onto a binary column as binary to avoid utf-8 interpretation, this is counter-productive!

The proper fix for this would be to implement the _binary flag in the conversion functions, fortunately there's an even easier way. It seems like you can use this statement at connect time to set the proper default collation:

    SET NAMES binary;

If you implement this in a patch, just make sure it also handle reconnections properly - the statement will have to be sent on reconnect too!

NB: It's probably best to use this statement *only* when using binary data storage.

**Comment by dermoth** [comment]
Also, I wish I could reproduce this but so far all MySQL version I tried didn't have this behavior. I used to have Debian Squeezy/Wheezy/Jessie MySQL(aka latest stable); and now just switched to MariaDB.

For my TokuDB one, I'm using mariadb-5.5.40-tokudb-7.5.3-linux-x86_64. I should probably try upgrading this one too...

**Comment by zontreck** [comment]
Currently using MySQL 5.5. It doesn't have the utf-8 warnings. But the OS is Mac.

**Comment by dermoth** [comment]
I can have you test a simple fix, but before I write one I need to know which version you're running *exactly* so I don't force you into upgrading abe database as well.

**Comment by zontreck** [comment]
MySQL 5.7.16 with the latest commit of Bitcoin-Abe

**Comment by dermoth** [comment]
Actually I might have a fix that doesn't involve any coding at all... please test it; if it works I'll document it in the sample configs. Just add `"init_command":"SET NAMES binary"` to your `connect-args` parameter in abe config, ex:

```
dbtype = MySQLdb
connect-args {"user":"abe","db":"abe","init_command":"SET NAMES binary"}
```

Let me know if that works...

**Comment by zontreck** [comment]
Didn't fix it

**Comment by dermoth** [comment]
Can you please export your schema using mysqldump (i.e. with --no-data) and send it?

Thanks

**Comment by dermoth** [comment]
Then I'm giving up... Where did your MySQL come from? Oracle, or some distro's build?? Any special MySQL configuration could explain this?

I couldn't reproduce it on multiple versions from Debian's MySQL and MariaDB packages, and also from a Tokutek build (now merged with Perconna's build, I haven't tried the latter). 

I'd consider this as a MySQL bug, especially when the columns are of binary types and using `SET NAMES binary`; there's just no good reason for MySQL to test for utf8 validity in this case. You should consider reporting a bug upstream...

**Comment by zontreck** [comment]
Oracle

**Comment by zontreck** [comment]
This same error happens on the current git code for MySQL.  Might be specific operating systems too. I'm using OS X. I'll consider this a MySQL Bug as well. Seems its been reported before and MySQL treats it as not a bug.

**Comment by dermoth** [comment]
If I'm not mistaken the rationale behind MySQL's decision was that the connection was utf8 and it's why it complained. Using `SET NAMES binary`, the connection charset should become binary and with the binary columns there shouldn't be any utf8 checking.

You can confirm the connection charset with the `STATUS` command.

**Comment by McRemco** [comment]
Is there a fix for this problem, the SET NAMES binary command didn't fix this but it looks like the invalid utf8 is read from the block hash BLOB.

**Comment by dermoth** [comment]
Well that's the problem... BLOB stands for Binary Large OBject. It's not UTF-8 specific and should accept any values, UTF-8 or not. Many of the values stored by Abe are hashes and scripts in the *binary* form - this halves the storage required for these values vs. hexadecimal text (used on DB backends that do not support binary storage, but you can force it too).

You may want to try different versions of the MySQL server (Oracle, Percona, MariaDB builds) or different version of the Python MySQLdb connector... If a specific version is affected you should open an issue for that specific component.

Regards,
