### ISSUE TITLE
how to fix this ???????????

### ISSUE THREAD

**Issue by mraksoll** [bitcoin-abe/bitcoin-abe#220]
c:\>python -m Abe.abe --config myconf.conf --commit-bytes 100000 --no-serve Skipping datadir D:\coins\btc: [Errno 2] No such file or directory: 'D:\\coins\\btc\\blk0001.dat' 

wtf ??? blk00001.dat need, where fix this bug ?

**Comment by dermoth** [comment]
First of all this is not a bug. blkfile loader relies on blockchain files being accessible, and this error is cascaded from your operating system when Abe tried to open the first block file and failed.

Possibles reasons are:

1. You didn't set up the path to bitcoind data dir properly (make sure the path contains `blkNNNN.dat` files).
2. You're running a node in pruning mode and it cleared those blocks.

Note that alternatively you can run Abe with the rpc loader, but it may still need the right path to read your bitcoind.conf file and find proper RPC access parameters. Furthermore rpc loader won't help with pruning mode (even if bitcoind was still able to fetch the pruned blocks on the network it would be **very** slow).

Regards,

**Comment by mraksoll** [comment]
how faster add on db all blocks ? i put db on ram disk end it only add 200 000+  bloks after 200 000 it's start be very slow :(  i use sqlite3 db

**Comment by dermoth** [comment]
3 blocks per second sounds rather good... with current blocks (2000-3000 tx/block I can barely catch up on standard spindle disks). The more transactions there is the slower it will be. Honestly I don't think sqlite3 is the best choice though. I don't think you can run inserter and readers separately on sqlite3 (I've been only able using libeatmydata - a tool that speed things up by disabling all locking and flushing therefore likely destroying the data if any crash or powerfail occurs), and it doesn't support binary format (smaller, which also mean less reads) and large integers (with over time turns out to very approximate block statistics).

Personally I would suggest MariaDB (The version of MySQL I personally recommend) with InnoDB plugin, or PostgreSQL, and to speed up inserts you may want to either run form a ramdisk or use libeatmydata, but be aware that doing so you put at risk any database in your MySQL/PostgreSQL.

Besides flushing, what can make loading slow is linking up to txouts, which involves accessing older tx entries. Running your database on a ramdisk or with eatmydata is one option, but properly tuning your database server hight help a lot as well.

For MySQL making the InnoDB buffer pool as large as possible might be as efficient as a ramdisk for reads (plus if the data size exceeds RAM you won't have to copy it all to disk to resume inserts!). 

For write performance, MySQL has some options too... mainly innodb_flush_log_at_trx_commit=2 but there are other settings you can play with. Using a raid controller with cache in writeback mode will also give you a huge speedup (note though without battery backup, WB cache mode it kinda like using libeatmydata).

Full SQL backups in MySQL are much faster than Abe import, soi be sure to back up yout database co you can recover or speed up new databases. SQL dumps are not compatible between different SQL engines though as we use various engine-specific tweaks.

Also make sure you set Abe commit-bytes to some large value so that inserts are batched (not too large as a process crash/abort will cause rollback, and the larger the batch is the longer the rollback can take and more inserted data will be lost). Right now largest blocks are pegged at 1M, so a batch size of 10M could rollback up to 20 blocks if average block size is 512k). I don't think going any higher than that will help a lot...

Final note, if the Python insert process is pegged at 100% CPU, there's nothing you can do to speed it up.

Regards

**Comment by mraksoll** [comment]
_mysql_exceptions.OperationalError: (1074, "Column length too big for column 'tx
out_scriptPubKey' (max = 65535); use BLOB or TEXT instead")

i try MariaDB end hv this error, i realy dont understand what do fo it;s start work with other db.

**Comment by mraksoll** [comment]
If it's possible you can give dump db mysql or what you use for fast insert ?
i dont know what to do for make work any db. Only work sqlite other nor work. End sqlite after size 6 gb corrupt. It's impossible to connect on bitcoin core end use include database on client ?

**Comment by mraksoll** [comment]
read db on client or read db client end insert only tables if they are requested ( if dont hv dump - it's hell insert all tables :(  )

**Comment by K1773R** [comment]
sheesh, just use a proper os and be done with it...

**Comment by dermoth** [comment]
Regarding the exception, are you using InnoDB tables? (you might have to enable the engine/plugin and make it the default...).  MySQL/MariaDB supports many different backend engines... default used to be MyISAM, Maria introduced a new default I think, and InnoDB always been optional. InnoDB is one of the best engines for large/io-intensive databases.

You can set the default in your abe connect options, though it may be ignored if you haven't enabled the engine:

    connect-args {<user/pass/db args>,"init_command":"SET default_storage_engine='InnoDB'"}

**Comment by dermoth** [comment]
FYI, looking at the code Abe should try using transactions with the default database engine *and then* with InnoDB. If default isn't transactional and InnoDB isn't available it would fail with an explicit error message.

MyISAM used to be non-transactional so it would force InnoDB, but if your default is transactional then you will have to set the default engine to InnoDB (and make sure it's enabled) as mentioned above.

If InnoDB is disabled I beliebe MySQL may fall back to another engine with warning and it may go on without InnoDB support.

Oh I assume you're using a 64bit build? It sounded like you had lots of RAM; 64bit is needed for a process to allocate more that 4G RAM (the actual limit will be 2 or 3G on a 32bit OS). As I said best use of your ram with InnoDB is to have everything leftover allocated to the innnodb buffer pool.

**Comment by mraksoll** [comment]
in all mysql db i hv this error

  File "c:\users\v\appdata\local\temp\easy_install-tb9wrp\MySQL_python-1.2.5-py2
.7-win32.egg.tmp\MySQLdb\cursors.py", line 205, in execute
  File "c:\users\v\appdata\local\temp\easy_install-tb9wrp\MySQL_python-1.2.5-py2
.7-win32.egg.tmp\MySQLdb\connections.py", line 36, in defaulterrorhandler
_mysql_exceptions.OperationalError: (1074, "Column length too big for column 'tx
out_scriptPubKey' (max = 65535); use BLOB or TEXT instead")

**Comment by mraksoll** [comment]
used mysql/mariadb x64

**Comment by mraksoll** [comment]
python version  is python 2.7.13

**Comment by mraksoll** [comment]
c:\>python -m Abe.abe --config myconf.conf --commit-bytes 100 --no-serve
ddl_implicit_commit=true
create_table_epilogue=''
max_varchar=10921
clob_type=LONGTEXT
binary_type=binary
int_type=int
sequence_type=mysql
limit_style=native
G:\Python27\lib\site-packages\Abe\SqlAbstraction.py:455: Warning: Truncated inco
rrect INTEGER value: 'foo'
  sql.cursor().execute(stmt, params)
G:\Python27\lib\site-packages\Abe\SqlAbstraction.py:455: Warning: Truncated inco
rrect INTEGER value: 'bar'
  sql.cursor().execute(stmt, params)
G:\Python27\lib\site-packages\Abe\SqlAbstraction.py:455: Warning: Truncated inco
rrect INTEGER value: 'baz'
  sql.cursor().execute(stmt, params)
G:\Python27\lib\site-packages\Abe\SqlAbstraction.py:455: Warning: Truncated inco
rrect DOUBLE value: 'foo'
  sql.cursor().execute(stmt, params)
G:\Python27\lib\site-packages\Abe\SqlAbstraction.py:455: Warning: Truncated inco
rrect DOUBLE value: 'bar'
  sql.cursor().execute(stmt, params)
G:\Python27\lib\site-packages\Abe\SqlAbstraction.py:455: Warning: Truncated inco
rrect DOUBLE value: 'baz'
  sql.cursor().execute(stmt, params)
((0L, 0L),)
(('foobarbaz', 'bazfoobar'),)
concat_style=mysql
Failed: CREATE TABLE txout (
    txout_id      NUMERIC(26) NOT NULL PRIMARY KEY,
    tx_id         NUMERIC(26) NOT NULL,
    txout_pos     NUMERIC(10) NOT NULL,
    txout_value   NUMERIC(30) NOT NULL,
    txout_scriptPubKey VARBINARY(1000000),
    pubkey_id     NUMERIC(26),
    UNIQUE (tx_id, txout_pos),
    FOREIGN KEY (pubkey_id)
        REFERENCES pubkey (pubkey_id)
)
Traceback (most recent call last):
  File "G:\Python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "G:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "G:\Python27\lib\site-packages\Abe\abe.py", line 2112, in <module>
    sys.exit(main(sys.argv[1:]))
  File "G:\Python27\lib\site-packages\Abe\abe.py", line 2106, in main
    store = make_store(args)
  File "G:\Python27\lib\site-packages\Abe\abe.py", line 156, in make_store
    store = DataStore.new(args)
  File "G:\Python27\lib\site-packages\Abe\DataStore.py", line 3415, in new
    return DataStore(args)
  File "G:\Python27\lib\site-packages\Abe\DataStore.py", line 191, in __init__
    store.initialize()
  File "G:\Python27\lib\site-packages\Abe\DataStore.py", line 838, in initialize

    store.ddl(stmt)
  File "G:\Python27\lib\site-packages\Abe\DataStore.py", line 263, in ddl
    store._sql.ddl(stmt)
  File "G:\Python27\lib\site-packages\Abe\SqlAbstraction.py", line 485, in ddl
    sql.cursor().execute(stmt)
  File "c:\users\v\appdata\local\temp\easy_install-habe9z\MySQL_python-1.2.5-py2
.7-win32.egg.tmp\MySQLdb\cursors.py", line 205, in execute
  File "c:\users\v\appdata\local\temp\easy_install-habe9z\MySQL_python-1.2.5-py2
.7-win32.egg.tmp\MySQLdb\connections.py", line 36, in defaulterrorhandler
_mysql_exceptions.OperationalError: (1074, "Column length too big for column 'tx
out_scriptPubKey' (max = 65535); use BLOB or TEXT instead")

**Comment by dermoth** [comment]
What is your default engine? Since it didn't specify ENGINE=InnoDB in the create table statement then you're using default.

Have you tried adding `"init_command":"SET default_storage_engine='InnoDB'"` to your connect-args parameters (as suggested earlier...)? 

What do you get for the following command in MySQL:

    SHOW ENGINES;

**Comment by vhaasteren** [comment]
I had the same error as in the OP "No such file or directory: 'D:\coins\btc\blk0001.dat", and I managed to work around that by renaming all my blk*.dat files such that there is a zero removed. So, I had to do "blk00001.dat" -> "blk0001.dat" etc.
