### ISSUE TITLE
sqlite3 error

### ISSUE THREAD

**Issue by Scalextrix** [bitcoin-abe/bitcoin-abe#223]
on the initial run of Abe I get this error:
    sqlite3.OperationalError: table configvar already exists

**Comment by dermoth** [comment]
Can you please paste the full error message - I'd expect a full backtrace if Abe dies on this.

Be sure to let Abe create the sqlite file - delete it first or use a different path.

Also FWIW you'd be better off using a real database engine such as Postgresql or MySQL... Those support more compact blob storage, have precision arithmetics, and allow concurrent readers/writers (so you have an import job in background while read-only webservers can access the same DB).

Regards

**Comment by Scalextrix** [comment]
steve@steve-Aspire-5740:~/blockchain-explorer-master$ sudo python -m Abe.abe --config abe-sqlite.conf --commit-bytes 100000 --no-serve
MAIN
ddl_implicit_commit=true
create_table_epilogue=''
max_varchar=4294967295
clob_type=CLOB
binary_type=buffer
int_type=str
sequence_type=update
limit_style=native
Failed: CREATE TABLE configvar (
    configvar_name  VARCHAR(100) NOT NULL PRIMARY KEY,
    configvar_value VARCHAR(255)
)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/steve/blockchain-explorer-master/Abe/abe.py", line 2332, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/steve/blockchain-explorer-master/Abe/abe.py", line 2326, in main
    store = make_store(args)
  File "/home/steve/blockchain-explorer-master/Abe/abe.py", line 106, in make_store
    store = DataStore.new(args)
  File "Abe/DataStore.py", line 3435, in new
    return DataStore(args)
  File "Abe/DataStore.py", line 173, in __init__
    store.initialize()
  File "Abe/DataStore.py", line 1221, in initialize
    store.ddl(stmt)
  File "Abe/DataStore.py", line 525, in ddl
    store.cursor.execute(stmt)
sqlite3.OperationalError: table configvar already exists

I could not find a .db file which I assume would be the sqlite database file, do you know where it would be located and its specific filename?

This is just an initial test, I just want to see if I can get Abe to run before installing different database environments, thanks for your help

**Comment by dermoth** [comment]
Look at the sqlite file path in your abe configuration (it's the `connect-args` parameter - make sure you have one defined/uncommented). I suspect you have an existing broken sqlite db and abe fails to detect a configured DB so it tries to create it which returns duplicate table errors.

Also make sure you're running a single Abe process for the import (parallelism only works for reads... Abe shouldn't be able to start multiple imports on the same sqlite file anyway... unless your OS/Sqlite file locking implementation is utterly broken).

**Comment by soheilade** [comment]
Hi guys,
can we query the sqlite db independently? did you discover where it is located? I am running .databases command in my sqlite and there is no database...

**Comment by dermoth** [comment]
I never tried `.databases`... have you tried `.tables`? It should either show the tables or give you some error due to file locking (at least on my Linux system I cannot read the db while Abe has it open for writing). If not thet you may have the wrong sqlite file or it got deleted/replaced by another app (in the later case the db file is deleted from filesystem point of view and its allocated blocks will be dropped when Abe process quits!)

You can work around file locking with libeatmydata - this is an LD_PRELOAD library that will disable locks and data flushing... with it the initial import should be much faster but a crash will most likely render your entire database unusable (it may be ok for initial load and if you take regular backups while Abe is not running)...

For any serious work I would highly recommend a read RDBMS like PostgreSQL or MySQL.

Regards
