### ISSUE TITLE
'ScryptJaneChain' object has no attribute 'start_time'

### ISSUE THREAD

**Issue by foxer666** [bitcoin-abe/bitcoin-abe#228]
Good day.

```
Failed to catch up {'blkfile_offset': 0, 'blkfile_number': 1, 'chain_id': 20, 'loader': u'blkfile', 'conf': u'cachecoin.conf', 'dirname': u'/home/mining/.cachecoin', 'id': 39L}
Traceback (most recent call last):
  File "Abe/DataStore.py", line 2557, in catch_up
    store.catch_up_dir(dircfg)
  File "Abe/DataStore.py", line 2843, in catch_up_dir
    store.import_blkdat(dircfg, ds, blkfile['name'])
  File "Abe/DataStore.py", line 2957, in import_blkdat
    hash = chain.ds_block_header_hash(ds)
  File "Abe/Chain/__init__.py", line 136, in ds_block_header_hash
    ds.input[ds.read_cursor : ds.read_cursor + 80])
  File "Abe/Chain/ScryptJaneChain.py", line 34, in block_header_hash
    return yac_scrypt.getPoWHash(header, b['nTime'] + YAC_START_TIME - chain.start_time)
AttributeError: 'ScryptJaneChain' object has no attribute 'start_time'
```

Where I must config start_time of coin?

Thanks.

**Comment by dermoth** [comment]
Can you please try from this branch: https://github.com/dermoth/bitcoin-abe/tree/ScryptJaneChain_start_time_fix

Regards

**Comment by foxer666** [comment]
Good day.
How config it in Abe.conf?
"policy":"ScryptJaneChain:1394480376",
"start_time":1394480376,
Some else?

**Comment by dermoth** [comment]
I don't know; never used it. Also note that block_id is an internal sequence, not related to the block_height.

After looking further It appears this is a base policy type, you need to subclass it to provide the actual chain parameters, including start_time.

See for example `Abe/Chain/Bitleu.py`

You can list policies with:

    python -m Abe.abe --list-policies

And get details about them:

~~~
$ python -m Abe.abe --show-policy ScryptJaneChain
ScryptJaneChain:
  A blockchain that uses Scrypt-Jane to hash block headers.
  The current implementation requires the yac_scrypt module.
  The ScryptJaneChain policy must be subclassed to provide the start_time
  parameter in Unix time_t format.
~~~

Regards

**Comment by foxer666** [comment]
Newermind.
Thanks.

**Comment by foxer666** [comment]
Sory, but iquidus work fine.

**Comment by dermoth** [comment]
@foxer666 so is the patch needed at all?

**Comment by foxer666** [comment]
Yes, ofcourse. Abe can use some different coins on one server, iquidus can't.
Thanks.

**Comment by foxer666** [comment]
No patch, no info about start_time to set it in config.

**Comment by dermoth** [comment]
This class is a base class on which you can base cryptocoins. You need to find out the missing info and create a new Chain class where you put the missing values. See `Abe/Chain/Bitleu.py` for instance.

**Comment by foxer666** [comment]
@dermoth 
Abe support Scrypt-Jane, but I must create my own chain?
```
from .ScryptJaneChain import ScryptJaneChain
from .PpcPosChain import PpcPosChain

class Bitleu(ScryptJaneChain, PpcPosChain):
    def __init__(chain, **kwargs):
        chain.name = 'Bitleu'
        chain.code3 = 'BTL'
        chain.address_version = "\x30"
        chain.script_addr_vers = '\x1b'
        chain.magic = "\xd9\xe6\xe7\xe5"
        chain.decimals = 6
        super(Bitleu, chain).__init__(**kwargs)

    datadir_conf_file_name = "Bitleu.conf"
    datadir_rpcport = 7997
    start_time = 1394480376
```
I understand all but this don't:
PpcPosChain
**kwargs

Thanks for help.

**Comment by dermoth** [comment]
Ok... I assume you do understand the import, then the `Bitleu` class is created based on both `ScryptJaneChain` and `PpcPosChain` classes, meaning new properties/methods and overrides will be inherited from *both* classes (maybe not what you want, depending on the chain you create, but you'll need `ScryptJaneChain` at the very least.

The `**kwargs` is a dict that takes keywords arguments (one star would be positional argument). methods can have at most one positional (list) argument and one keyword (dict) argument that will capture all positional/keyword arguments (in this case only keywords, so there can be no positional args).

`kwargs` is merely passed on to the super class. Since it's Abe that defines the base class *and* initializes it, it's unlikely you'll have to modify it.
