### ISSUE TITLE
Abe unable to read block 100976

### ISSUE THREAD

**Issue by mikercline** [bitcoin-abe/bitcoin-abe#254]
I am trying to run Abe on CentOs 7. I am using Python 2.7.5, I downloaded Abe early January 2018. I have bitcoin core running successfully, and my blockchain is completely up to date. Abe ran from January 4 to January 26 without issue. It is trying to parse block 100976 and is failing with the issue below.

Exception at 12096905734078701433
Failed to catch up {'blkfile_offset': 27934628, 'blkfile_number': 100976, 'chain_id': None, 'loader': None, 'dirname': '/home/sealab/.bitcoin', 'id': Decimal('2')}
Traceback (most recent call last):
  File "Abe/DataStore.py", line 2563, in catch_up
    store.catch_up_dir(dircfg)
  File "Abe/DataStore.py", line 2843, in catch_up_dir
    store.import_blkdat(dircfg, ds, blkfile['name'])
  File "Abe/DataStore.py", line 2965, in import_blkdat
    b = chain.ds_parse_block(ds)
  File "Abe/Chain/__init__.py", line 82, in ds_parse_block
    d['transactions'].append(chain.ds_parse_transaction(ds))
  File "Abe/Chain/__init__.py", line 75, in ds_parse_transaction
    return deserialize.parse_Transaction(ds)
  File "Abe/deserialize.py", line 93, in parse_Transaction
    d['txIn'].append(parse_TxIn(vds))
  File "Abe/deserialize.py", line 46, in parse_TxIn
    d['sequence'] = vds.read_uint32()
  File "Abe/BCDataStream.py", line 71, in read_uint32
    def read_uint64 (self): return self._read_num('<I')
  File "Abe/BCDataStream.py", line 110, in _read_num
    (i,) = struct.unpack_from(format, self.input, self.read_cursor)
OverflowError: Python int too large to convert to C long

The abe.conf file that I am using says:
dbtype MySQLdb
connect-args {"user":"abe","db":"abe","passwd":"************"}
upgrade
port 2750

Any ideas on how to move past this? When I check the database, I am only current in mysql to August of 2017.

**Comment by dermoth** [comment]
Can you make sure you're using a 64bit version of Python 2.7? If you are, then this particular block may be corrupted.

FWIW you're going to have issues with Segwit blocks that started much later (past the 400k mark; segwit is not fully supported yet), but these older blocks should load without any issue.

**Comment by mikercline** [comment]
When I run the following command:
python -c 'import sys;print("%x" % sys.maxsize, sys.maxsize > 2**32)'
I get the following output:
('7fffffffffffffff', True)

To my understanding that means I am using 64 bit python. How can I correct a corrupted block?

Thank you for letting me know about the Segwit blocks. Is there a time frame for when these will be fully supported?

**Comment by dermoth** [comment]
I tried to add support to segwit blocks but I didn't finish yet and don't really have time for that at this point... what doesn't help is that I no longer have sufficient hardware to keep Abe up to date with current volume... I can test on testnet but won't even be able keep mainnet sync.

The current work is pushed to my fork, so if anyone wants to pick it up it can be done. I've done the block/tx decoding part but schema changes needs to be done to support segwit data... and frontend support as well.

You can always run a pre-segwit bitdoind that will offer non-segwit blocks to Abe. However the day you make the switch both bitcoind and Abe will have to rollback all blocks and restart from the Segwit softfork (that rollback code has to be written too... should be part of the schema upgrade).

Regards

**Comment by ZielarSRC** [comment]
As I have been searching for a solution for a very long problem for a long time - I am presenting a solution that has been helpful to me:

1. In the configuration file (in my case: abe-my.conf), add a line:
`
key-type=str
`
2. We download Bitcoin Core version 0.13.1 on which it is necessary to synchronize blocks with the blockchain from scratch (it must be done from scratch, without combining with the underlay of blocks from newer Bitcoin Core releases)

3. After synchronizing - the starting procedure is the same as in the original version in which there is a problem ... with the difference that ... bitcoin-abe synchronizes successive blocks after crossing the block currently creating the problem :-)

I hope I helped :-)

**Comment by blackdimund** [comment]
> As I have been searching for a solution for a very long problem for a long time - I am presenting a solution that has been helpful to me:
> 
> 1. In the configuration file (in my case: abe-my.conf), add a line:
>    `key-type=str`
> 2. We download Bitcoin Core version 0.13.1 on which it is necessary to synchronize blocks with the blockchain from scratch (it must be done from scratch, without combining with the underlay of blocks from newer Bitcoin Core releases)
> 3. After synchronizing - the starting procedure is the same as in the original version in which there is a problem ... with the difference that ... bitcoin-abe synchronizes successive blocks after crossing the block currently creating the problem :-)
> 
> I hope I helped :-)

Is 0.13.1 supposed to avoid the segwit stuff in bitcoin core? And what is the key-type, where do I find information on that?

**Comment by dermoth** [comment]
1. I don't think the key-type is your issue - using str will make the database significantly larger though.

2. There is code in my fork to read segwit blocks but not to import the data, which I believe should make a difference only if you use keep-scriptsig. One issue is that all blocks would have to be reimposted after switching to segwit if we finish support (this is also what Bitcoin 14+ does after upgrading...)

3. What was the error did you get exactly? It could have been database corruption.... I've also seen odd things happening with Abe import, sometimes the stats breaks and I haven't been able to find the issue.
