### ISSUE TITLE
Can't Serve Abe

### ISSUE THREAD

**Issue by bitcoinstant** [bitcoin-abe/bitcoin-abe#268]
I configured the software for Bitcoin Instant, adding in the proper Datastore.py code needed so there would be a class for Instantcoin.  Now when I launch using:

    sudo python -m Abe.abe --config abe-pg.conf

I see:

    Abe initialized.
    Listening on http://localhost:80

But I don't see my server on abe.getbitcoininstant.org

pls halp. my familia

**Comment by Lvl4Sword** [comment]
Can you try running Abe without sudo? What does your .conf look like?

**Comment by bitcoinstant** [comment]
dbtype = psycopg2
connect-args = { "database": "abe" }
upgrade
port 80
host localhost

**Comment by bitcoinstant** [comment]
can't run w/out sudo

**Comment by Lvl4Sword** [comment]
You can't run without sudo because you're setting your port to 80 ( which, anything under 1024 is considered special ). Are you using Apache or nginx? Go into either of these and set a proxy pass from the internal Abe port ( which you should switch from 80 to the default 2750 ) to an external port of something like 80/443.

Something like the following should work for Apache:

    <VirtualHost *:443>
    ServerName example.com

    SSLEngine On
    SSLProxyEngine On

    SSLCertificateFile /etc/letsencrypt/live/example.com/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/example.com/privkey.pem

    LoadModule  proxy_module         /usr/lib/apache2/modules/mod_proxy.so
    LoadModule  proxy_http_module    /usr/lib/apache2/modules/mod_proxy_http.so
    LoadModule  headers_module       /usr/lib/apache2/modules/mod_headers.so
    LoadModule  deflate_module       /usr/lib/apache2/modules/mod_deflate.so

    ProxyVia On
    ProxyRequests Off
    ProxyPass / http://localhost:2750/
    ProxyPassReverse / http://localhost:2750/$1/
    ProxyPreserveHost On
    <Proxy *>
        Options FollowSymLinks MultiViews
        AllowOverride All
        Order allow,deny
        allow from all
    </Proxy>

    <Directory "/home/abe/Abe/htdocs/">
        Require all granted
    </Directory>

</VirtualHost>

**Comment by bitcoinstant** [comment]
No. I can't run w/out sudo because:

    getbitcoininstant:~/bitcoin-abe$ python -m Abe.abe --config abe-pg.conf

Output:

    ddl_implicit_commit=false
    create_table_epilogue=''
    max_varchar=10485760
    clob_type=TEXT
    binary_type=hex
    int_type=int
    sequence_type=postgres
    limit_style=native
    [('foobarbaz', 'bazfoobar')]
    concat_style=ansi
    Failed: CREATE TABLE configvar (
        configvar_name  VARCHAR(100) NOT NULL PRIMARY KEY,
        configvar_value VARCHAR(255)
    )
    Traceback (most recent call last):
      File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/home/owsley/bitcoin-abe/Abe/abe.py", line 2123, in <module>
        sys.exit(main(sys.argv[1:]))
      File "/home/owsley/bitcoin-abe/Abe/abe.py", line 2117, in main
        store = make_store(args)
      File "/home/owsley/bitcoin-abe/Abe/abe.py", line 156, in make_store
        store = DataStore.new(args)
      File "Abe/DataStore.py", line 3429, in new
        return DataStore(args)
      File "Abe/DataStore.py", line 193, in __init__
        store.initialize()
      File "Abe/DataStore.py", line 840, in initialize
        store.ddl(stmt)
      File "Abe/DataStore.py", line 265, in ddl
        store._sql.ddl(stmt)
      File "Abe/SqlAbstraction.py", line 497, in ddl
        sql.cursor().execute(stmt)
    psycopg2.ProgrammingError: relation "configvar" already exists

**Comment by bitcoinstant** [comment]
And I am not running any reverse proxy scheme using a web host such as nginx or apache.  I understand there are benefits and have run either.  I assumed the python web server was good enough and didn't run either nginx or apache.

**Comment by bitcoinstant** [comment]
I fixed it.

host needed to be 0.0.0.0
    host 0.0.0.0

not 

    host localhost

This config works

    dbtype = psycopg2
    connect-args = { "database": "abe" }
    upgrade
    port 80
    host 0.0.0.0

^ works

**Comment by Lvl4Sword** [comment]
https://github.com/bitcoin-abe/bitcoin-abe/blob/master/README-POSTGRES.txt doesn't reference host, and I'm not sure why you believe you need it. Are you running Abe as root?
