### ISSUE TITLE
Mysql initial load is too slow!

### ISSUE THREAD

**Issue by Mahla-ch** [bitcoin-abe/bitcoin-abe#269]
hello,
I've been running this project for 14 days but it is not finish yet! the last number of block is 274853 in mysql database!! it is too slow!!!
Is it because of Mysql? should I change my database to sqlite or something else?

These are my system config:
CPU: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
RAM: 4G
OS: Ubuntu 16.04
Internet speed: 1000 Mb/s

**Comment by Lvl4Sword** [comment]
Do you have at least 170,000MB free for the blockchain? ( https://blockchain.info/charts/blocks-size )

**Comment by Lvl4Sword** [comment]
What is the output of the command `python -m Abe.abe --config abe-my.conf --commit-bytes 100000 --no-serve`? Should be something like `block_tx 1 1 block_tx 2 2`

**Comment by Mahla-ch** [comment]
these are the last output of that command:
block_tx 278823 30476268
block_tx 278823 30476269
block_tx 278823 30476270
block_tx 278823 30476271
block_tx 278823 30476272
...

**Comment by Lvl4Sword** [comment]
Is it still appending or has it frozen? If it's still appending, I'd suggest waiting and letting it finish. If it's frozen, that's an issue.

**Comment by Mahla-ch** [comment]
It's still appendig but very slowly! 5000 blocks in a day isn't abnormal? downloading blockchain was more fast!
Do you know the reason? Is it about mysql or my system config?

**Comment by BarrowHill** [comment]
I have the same issue, "slow bitcoin abe".
I was running abe 24/7, 30 days on SSD 500Gb, when size of abe database excceded 340Gb ( at block_tx 462662 212564751) I have transfered abe MySQL database (InnoDB) to 2Tb HDD, sinche then I'm ruuning about about 2000 blocks a day, so it will finish about year 2019!
my config Xeon X3363 @3..6GHz (quad core)/8Gb RAM/SSD Samsung EVO850 500Gb/HDD 2Tb/Windows 7 x64/
I have left logfiles in SSD and transfred to HDD just MySQL abe DB with symlink.
 I think we can achieve a good speed with tuning MySQL config file. If there any experienced MySQL DB user here please help us.
some of my MySQL settings
innodb_flush_log_at_trx_commit = 2
innodb_buffer_pool_instances=3
innodb_buffer_pool_size = 2560M
innodb_checksum_algorithm=none
innodb_concurrency_tickets=5000
innodb_log_buffer_size = 32M
innodb_log_file_size = 512M
innodb_log_files_in_group = 2
innodb_max_dirty_pages_pct = 90
innodb_old_blocks_time=1000
innodb_read_io_threads = 8
innodb_stats_on_metadata=0
innodb_thread_concurrency=4
innodb_write_io_threads = 8
innodb_io_capacity_max=200
innodb_io_capacity=100 (this is recommended for HDD, for SSD it sould be 1000-2000)

**Comment by BarrowHill** [comment]
After probing with different MySQL confugartions, reading more than 100 posts about how to optimize InnoDB, how to speed up MySQL server, nothing helped! The more I was playing with config file the worst result I was achieving. THE ONLY solution is TO SPREAD MySQL tables to the different physical disks!
So, I have found a solution, we need to transfer MySQL DB files to another disks. MySQL is very slow with abe because it is working with 6 DB files at the same time + log files + ibdata file.
 So, in order to move a DB file to another locations we need.
1. Stop MySQL server
2. move pubkey.ibd to another HDD/SSD drive (for example, to drive D)
3. create in original location a file with pubkey.isl (*.isl extension) and write there the new directory for that table, e.g. D:/abe2/pubkey.ibd
4. start MySQL server and run bitcoin abe.
This way you can move another tables to the next phisical drive E, NOT LOGICAL!!! But to another physical HDD or SSD drive!
So, this way we need to spread all huge tables to separate disk, this tables are:
1) pubkey.ibd
2) block_txin.ibd
3) block_tx.ibd
4) tx.ibd
5) txout.ibd   (this is the biggest table)
6) txin.ibd
Hope it will help you a lot! Have a nice day!

**Comment by dermoth** [comment]
If you use SSD you shouldn't need multiple disks as seek time is pretty much irrelevant with them, but be careful as you might wear out consumer-grade disks pretty quickly. If you only have space for few tables, your best luck is to enable performance data collection in mysql and check which tables it spends most time doing reads - put those on your SSD's,

The redo logs and doublewrite buffers can easily go on normal spinning disks - that would save writes on your ssd. A battery-backed up raid would be best so writes return faster. IIRC if you use file_per_table there isn't much left in the system tablespace aside from the undo log, so that can go wherever... either SSD or separate disk (to prevent contention with logs/doublewrite).

Then all your tables on SSD would ensure fastest possible reads during index lookups, which is the slowest part of the whole process. If you can allocate enough RAM for InnoDB for the whole table data that's even better, but on cold start the data needs to be read in anyway.

On Abe side, make sure you use the latest RPC code and have Abe load mempool between blocks - once you caught up it will speed up significantly insert of new blocks.

-----

FYI, if you got good coding skills, I have toyed with the idea of changing drastically the database but never had time to write something meaningful... If we removed all sequences and used binary hashes for primary keys, then we could speed up inserts significantly in two way:

1. Inserting data could be done directly - Instead of looking up reference hashes to get id's, you could insert foreign keys directly as you already know them from the blocks - you'd save a lots of round-trips to read block and tx id's from database before inserting them.

2. For those who feel adventurous, disabling keys and blindly trusting Bitcoind data - inserts would be mostly writes with only reads needed to update btrees. TokuDB would probably be the best choice for this (and it doesn't support checking foreign keys anyway). That would probably be the only option for slower disks.

**Comment by BarrowHill** [comment]
dermoth, I'm now on 24Gb RAM, Xeon X5760, 2xSSD, 2xHDD. so I can 100% tell you that abe don't need more RAM, because I have set buffer pool to 16Gb (and the same speed when I start from the beggining), then I drop all tables into abe, because it was stacks at error:
'duplicate entry' at key PRIMARY
.So I start it again! The same speed! about 5000 transactions per minute, so it will take about 3-6 month to load all blocks and transactions. so please, improve pyton code or something else. (python CPU usage 3%)
in my abe.conf file:
default-loader = blkfile
rpc-load-mempool
#host 127.0.0.1
#port 2750
datadir = F:\Bitcoin
dbtype MySQLdb
    connect-args {"user":"root","db":"abe","passwd":""}
    upgrade
    port 2750

Is my config file right? I even tried to transfer ibdata and log file into RAM disk, nothing helps( Please improve the code.

**Comment by BarrowHill** [comment]
dermoth, could you transfer this project into pyhton 3? Maybe this will help?

**Comment by BarrowHill** [comment]
now I've got error
IntegrityError: (1062, "Duplicate entry '1037895' for key 'PRIMARY'")
Could you tell me how to resolve this issue?
What I need to delete in abe through phpMyAdmin ? Just find table with 1037895 row and delete it?

**Comment by dermoth** [comment]
If you get integrity errors after power failures it means either you have writeback caching somewhere on your storage or your storage lies about data being orderly written to disk. You can turn on debug logging to see which insert fails exactly. In any case it wouldn't be safe to trust a database which cannot support a power failure (I had many power fail and no import failures on MySQL and MariaDB (Innodb).

On the speed issue, if python is running at 3% cpu then it's definitively not the bottleneck - with fast storage it should be almost pinned at 100% I don't think python3 would help neither, my experience is that the new strict string encoding in Python3 can actually make scripts significantly slower (probably not so much for Abe if we can handle everything as bytes). I also have a feeling form working with the code that Python3 conversion for Abe would be a huge undertaking.

Asides from changing the whole DB design to use hashes as primary keys, which would allow to disable key checks for fast inserts (assuming we can trust Bitcoind's data quality), the only solution I see would be to have enough RAM to fit the whole data in it. I stopped syncing at block *480811* and my database is over 300GB with table compression, so your mere 24G is clearly not enough - I'm talking 600G+ servers there, or shading across many (sharding would likely incur slightly added latency, so better to have one backend DB for speed).

SSD storage should help a lot too, especially on warmup (when the data isn't loaded into ram after a restart). The issue if that right now to insert a transaction it first need to find **for each tx input** the block **id** from the block number and tx/txin **id**. That's a lot of reads before it can even insert the new transaction and I'm pretty sure this is where all your import time is spent.

**Comment by dermoth** [comment]
BTW if you want to use ramdisk, and assuming you're using file_per_table, it's the actual tables that would have to be placed in ramdisk (the *.ibd files in the database's subdirectory). 24G ram is very far from being enough for that.

If you only have limited space on ram/ssh, the best option is to find the tables MariaDB spends the most time reading from (you need to enable performance counters in MariaDB for that) and move only those to ram or ssd... but iirc the # 1 culprit is txin.ibd and even back at block 480811 it was over 100GB!

**Comment by BarrowHill** [comment]
1)When I start abe from the beggining I was trued out even to move mysql with abe to a RAM disk, even in this case import speed is about 5000-10.000 transactions per sec. Which means we need about 3 month, which is very long time for 350.000.000 transactions. 
2)MySQL warmup time is about 5-10 minutes, in that time I see more read from disks then writes. After warming up, now it's running and I will make a screenshot -> [http://prntscr.com/mf9hqr](url). When I moving ibdata1 to RAM disk, nothing changes, + moving logfile nothing changes too. When I'm closing Windows CMD windows (stopping abe), disk write speed is going up about 5-10 times. After 2 minutes mysql stops working.
3)I think speed will go up if you could optimeze some of *.py files which used Abe, If you could find that, it would be great.
4)Abe writes so many information, which I actually don't need. Right now I need only addresses and balances. Could we turn of writing some columns like I did in abe.conf file?
keep-scriptsig=false

**Comment by BarrowHill** [comment]
This is OSpanel 5.2.2 Mysql debug log
2019-02-01T07:36:14.988078Z 0 [Note] c:\ospanel\modules\database\MySQL-5.7-x64\bin\mysqld.exe (mysqld 5.7.20-log) starting as process 8812 ...
2019-02-01T07:36:15.192089Z 0 [Note] InnoDB: Mutexes and rw_locks use Windows interlocked functions
2019-02-01T07:36:15.192089Z 0 [Note] InnoDB: Uses event mutexes
2019-02-01T07:36:15.192089Z 0 [Note] InnoDB: _mm_lfence() and _mm_sfence() are used for memory barrier
2019-02-01T07:36:15.193089Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.3
2019-02-01T07:36:15.193089Z 0 [Note] InnoDB: Number of pools: 1
2019-02-01T07:36:15.193089Z 0 [Note] InnoDB: Not using CPU crc32 instructions
2019-02-01T07:36:15.205090Z 0 [Note] InnoDB: Initializing buffer pool, total size = 9G, instances = 12, chunk size = 128M
2019-02-01T07:36:15.780123Z 0 [Note] InnoDB: Completed initialization of buffer pool
2019-02-01T07:36:17.947247Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
2019-02-01T07:36:18.865299Z 0 [ERROR] InnoDB: Operating system error number 2 in a file operation.
2019-02-01T07:36:18.865299Z 0 [Note] InnoDB: Some operating system error numbers are described at http://dev.mysql.com/doc/refman/5.7/en/operating-system-error-codes.html
2019-02-01T07:36:18.865299Z 0 [ERROR] InnoDB: Cannot open datafile for read-only: 'G:\abe4\block.ibd' OS error: 71
2019-02-01T07:36:18.866300Z 0 [ERROR] InnoDB: A link file was found named '.\abe\block.isl' but the linked tablespace 'G:\abe4\block.ibd' could not be opened read-only.
2019-02-01T07:36:18.879300Z 0 [ERROR] InnoDB: Operating system error number 2 in a file operation.
2019-02-01T07:36:18.879300Z 0 [Note] InnoDB: Some operating system error numbers are described at http://dev.mysql.com/doc/refman/5.7/en/operating-system-error-codes.html
2019-02-01T07:36:18.879300Z 0 [ERROR] InnoDB: Cannot open datafile for read-only: 'G:\abe4\txin.ibd' OS error: 71
2019-02-01T07:36:18.879300Z 0 [ERROR] InnoDB: A link file was found named '.\abe\txin.isl' but the linked tablespace 'G:\abe4\txin.ibd' could not be opened read-only.
2019-02-01T07:36:18.899301Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2019-02-01T07:36:18.900301Z 0 [Note] InnoDB: Setting file 'c:\ospanel\userdata\MySQL-5.7-x64\ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2019-02-01T07:36:18.978306Z 0 [Note] InnoDB: File 'c:\ospanel\userdata\MySQL-5.7-x64\ibtmp1' size is now 12 MB.
2019-02-01T07:36:18.980306Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
2019-02-01T07:36:18.980306Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
2019-02-01T07:36:18.981306Z 0 [Note] InnoDB: 5.7.20 started; log sequence number 1051172837438
2019-02-01T07:36:18.982306Z 0 [Note] Plugin 'FEDERATED' is disabled.
2019-02-01T07:36:18.999307Z 0 [Note] Server hostname (bind-address): '127.0.0.1'; port: 3306
2019-02-01T07:36:19.000307Z 0 [Note]   - '127.0.0.1' resolves to '127.0.0.1';
2019-02-01T07:36:19.000307Z 0 [Note] Server socket created on IP: '127.0.0.1'.
2019-02-01T07:36:20.240378Z 0 [Note] Event Scheduler: Loaded 0 events
2019-02-01T07:36:20.241378Z 0 [Note] c:\ospanel\modules\database\MySQL-5.7-x64\bin\mysqld.exe: ready for connections.
Version: '5.7.20-log'  socket: ''  port: 3306  MySQL Community Server (GPL)
2019-02-01T07:36:27.945819Z 0 [Note] InnoDB: page_cleaner: 1000ms intended loop took 8964ms. The settings might not be optimal. (flushed=36 and evicted=0, during the time.)
2019-02-01T10:31:44.600337Z 0 [Note] InnoDB: page_cleaner: 1000ms intended loop took 7089ms. The settings might not be optimal. (flushed=144 and evicted=0, during the time.)
2019-02-01T10:35:07.950968Z 0 [Note] InnoDB: page_cleaner: 1000ms intended loop took 8160ms. The settings might not be optimal. (flushed=144 and evicted=0, during the time.)
2019-02-01T11:39:19.063239Z 0 [Note] InnoDB: page_cleaner: 1000ms intended loop took 4046ms. The settings might not be optimal. (flushed=144 and evicted=0, during the time.)
2019-02-01T13:11:11.915556Z 0 [Note] InnoDB: page_cleaner: 1000ms intended loop took 6514ms. The settings might not be optimal. (flushed=144 and evicted=0, during the time.)
2019-02-01T14:03:55.732516Z 0 [Note] InnoDB: page_cleaner: 1000ms intended loop took 5151ms. The settings might not be optimal. (flushed=156 and evicted=0, during the time.)

**Comment by BarrowHill** [comment]
I just measure, right now my insert speed is 5400 transactions per minute

**Comment by BarrowHill** [comment]
In scrrenshot N1 you can see that 
5)Innodb_buffer_pool_bytes_dirty is about 2.2 times higher than Innodb_buffer_pool_bytes_data is this normal?
6)Innodb_rows_inserted is the same, more than 2 times higher than Innodb_rows_deleted .
So THIS IS THE PROBLEM I THINK. Why so many Innodb_rows_deleted ?? Why Abe writes 36.000.000 rows and delete 16.000.000 rows???

**Comment by BarrowHill** [comment]
MOST important question right now.
7)When I'm running Abe on http://127.0.0.1:2750, For example I search block number 260.000. It shows me a lot of information which I don't need. I will mark them with "-", and please tell me how could we exclude them from being inserted into Abe database? Could we do this by adding some lines into abe.config file? Or you need to change some lines in some *.py files in Abe folder??
______
Bitcoin 260000
Short Link: http://127.0.0.1:2750/b/GfAL8aJ3T

Hash: 000000000000001fb91fbcebaaba0e2d926f04908d798a8b598c3bd962951080
Previous Block: 000000000000000057ffed43d607a5db036fe78f00c13852c8c9bca3518966ae
Next Block: 0000000000000006bda8a9646243754929a49cbe92a1312ad9623468cf99b9f3
Height: 260000
-Version: 2
-Transaction Merkle Root: 800bea3014bde6571717c84b6afb15573d6f882180e17a2b8546bdaff30540d7
Time: 1380094172 (2013-09-25 11:29:32)
-Difficulty: 112 630 267.267 (Bits: 19262222)
-Cumulative Difficulty: 1 259 350 336 133.351
-Nonce: 1270371778
Transactions: 156
Value out: 3862.66959163
Transaction Fees: 0.06917088
-Average Coin Age: 492.971 days
-Coin-days Destroyed: 1096.6696754
-Cumulative Coin-days Destroyed: 43.9223%
Transactions
Transaction | Fee | Size (kB) | From (amount) | To (amount)
-- | -- | -- | -- | --
b464510c7a... | 0 | 0.102 | Generation: 25 + 0.06917088 total fees | 1BxD2VLE95n7ZeVJSy3uoiJ5WdR72jWj5f: 25.06917088
______

**Comment by BarrowHill** [comment]
If we look here -> http://127.0.0.1:2750/address/16NsFTH1jYxHjNrHQ5aBGspxpgxSohccL5

Address 16NsFTH1jYxHjNrHQ5aBGspxpgxSohccL5
Short Link: http://127.0.0.1:2750/a/16NsFTH1jY

Balance: 0 BTC
Transactions in: 34
Received: 236.34816904 BTC
Transactions out: 34
Sent: 236.34816904 BTC

Transaction | Block | Approx. Time | Amount | Balance | Currency
-- | -- | -- | -- | -- | --
9e311b8acd... | 126371 | 2011-05-24 21:08:04 | 0.01 | 0.01 | BTC

I don't need currency column which rows all are "BTC", is it stored into MySQL tables? Or is generated on the fly by Abe.py?

**Comment by dermoth** [comment]
Are you really running this on windows?? Besides that I just wasn't sure abe would work on it, I'm not convinced of MySQL's performance on Windows - I'm sure a lot more tuning has gone on the Linux version. I'm also suspecting block loading, whenever using blkfile or RPC, might be a bit slower.

Regarding your first reply:

1. You can't compare load speed of initial block and later blocks - most blocks in the first 100k have no more then 1 tx per block, so what  you're seeing is the block import time rather than tx import time. If you use RPC it's even worse as each block requires one RPC call (blkfile reader may be better initially, but I highly recommend RPC import regardless as it will import blocks sequentially and will not import forks). As you get into larger blocks the RPC cost will become minimal and a ram-based database should be much faster. If Python isn't running at 100% CPU, it's either that it's waiting on bklfile read or RPC reply from bitcoind, or waiting on the database reads or commits (make sure you batch commits too, it's an option in abe.conf).

2. If you run from RAM you shouldn't see mysql reads - only logfile writes if those aren't in RAM. I suspect you use file_per_table, so your ibdata contains only undo buffer and doublewrite buffer, and all data you're hoping to put in ram is actually in the abd/*.ibd files. Those are the one that would benefif being in RAM or fast SSD/NVME.

3. If python doesn't use CPU, there is no point in optimizing it. First fix the storage backend, then when python is stuck at 100% cpu on import we can think of Python optimizations.

4. Yes, `keep-scriptsig=false` will help, and also if you run my partial segwit support branch then you whouldn't have to worry about it being incomplete as the only thing missing is scriptsig-related.

**Comment by dermoth** [comment]
Regarding the deletes, I suspect this is the sequences implemented as tables on MySQL - these shouldn't cause much IO anyway because that won't even have time to make it to disk if you batch imports.

You could try with PostgreSQL, but I have much less experience with pgsql tuning.

**Comment by dermoth** [comment]
#7 Removing information from db... besides keep-scriptsig you would have to play with the code iself, and I don'T think there' much you could do anyway.

If all you need is the balance, you could re-use the block decode pars and implement your own database backend, saving only what you need. Keep in ming though Abe is licensed under LGPL so any hosted site based on it must also redistribute the code it runs if it's even remotely based on Abe.

**Comment by dermoth** [comment]
Your last comment - BTC is the chain you use... if you have multiple chains then transaction show which chain (aka currency) they're in.

Abe supports loading multiple chain in the same database, which can be mostly useful for merged-mining chains where the same block apply to multiple chains (saves some duplicate data).

**Comment by dermoth** [comment]
Correction - Abe is AGPL - this is what I meant to say earlier. LGPL allow linking against code that isn't GPL and distributing the compiled libraries, ex. for compiled libraries; AGPL is much more strict and you can't even host a web service without distributing the code it's running.

**Comment by BarrowHill** [comment]
after deleting "Nonce" function fom abe.py datastore.py and some other files, I have stucked right now at
$ python -m Abe.abe --config abe.conf --no-serve
Opened F:\Bitcoin\blocks\blk00000.dat
Exception at 72056513014792326
Failed to catch up {'blkfile_offset': 0, 'blkfile_number': 100000, 'chain_id': None, 'loader': None, 'conf': None, 'dirname': 'F:\\Bitcoin', 'id': 39L}
Traceback (most recent call last):
  File "Abe\DataStore.py", line 2552, in catch_up
    store.catch_up_dir(dircfg)
  File "Abe\DataStore.py", line 2850, in catch_up_dir
    store.import_blkdat(dircfg, ds, blkfile['name'])
  File "Abe\DataStore.py", line 2972, in import_blkdat
    b = chain.ds_parse_block(ds)
  File "Abe\Chain\__init__.py", line 82, in ds_parse_block
    d['transactions'].append(chain.ds_parse_transaction(ds))
  File "Abe\Chain\__init__.py", line 75, in ds_parse_transaction
    return deserialize.parse_Transaction(ds)
  File "Abe\deserialize.py", line 90, in parse_Transaction
    d['txIn'].append(parse_TxIn(vds))
  File "Abe\deserialize.py", line 46, in parse_TxIn
    d['sequence'] = vds.read_uint32()
  File "Abe\BCDataStream.py", line 71, in read_uint32
    def read_uint32 (self): return self._read_num('<I')
  File "Abe\BCDataStream.py", line 110, in _read_num
    (i,) = struct.unpack_from(format, self.input, self.read_cursor)
error: unpack_from requires a buffer of at least 4 bytes

Help please!

**Comment by BarrowHill** [comment]
Now I have droped all tables inside abe. And running
1)
python -m Abe.abe --config abe.conf --no-serve
ddl_implicit_commit=true
create_table_epilogue=''
max_varchar=10921
clob_type=LONGTEXT
binary_type=binary
int_type=int
sequence_type=mysql
limit_style=native
((0L, 0L),)
(('foobarbaz', 'bazfoobar'),)
concat_style=mysql
Opened F:\Bitcoin\blocks\blk00000.dat
Exception at 72056513014792326
Failed to catch up {'blkfile_offset': 0, 'blkfile_number': 100000, 'chain_id': None, 'loader': None, 'conf': None, 'dirname': 'F:\\Bitcoin', 'id': 1L}
Traceback (most recent call last):
  File "Abe\DataStore.py", line 2552, in catch_up
    store.catch_up_dir(dircfg)
  File "Abe\DataStore.py", line 2850, in catch_up_dir
    store.import_blkdat(dircfg, ds, blkfile['name'])
  File "Abe\DataStore.py", line 2972, in import_blkdat
    b = chain.ds_parse_block(ds)
  File "Abe\Chain\__init__.py", line 82, in ds_parse_block
    d['transactions'].append(chain.ds_parse_transaction(ds))
  File "Abe\Chain\__init__.py", line 75, in ds_parse_transaction
    return deserialize.parse_Transaction(ds)
  File "Abe\deserialize.py", line 90, in parse_Transaction
    d['txIn'].append(parse_TxIn(vds))
  File "Abe\deserialize.py", line 46, in parse_TxIn
    d['sequence'] = vds.read_uint32()
  File "Abe\BCDataStream.py", line 71, in read_uint32
    def read_uint32 (self): return self._read_num('<I')
  File "Abe\BCDataStream.py", line 110, in _read_num
    (i,) = struct.unpack_from(format, self.input, self.read_cursor)
error: unpack_from requires a buffer of at least 4 bytes
Abe\SqlAbstraction.py:467: Warning: Truncated incorrect DOUBLE value: 'foo'
  sql.cursor().execute(stmt, params)
Abe\SqlAbstraction.py:467: Warning: Truncated incorrect DOUBLE value: 'bar'
  sql.cursor().execute(stmt, params)
Abe\SqlAbstraction.py:467: Warning: Truncated incorrect DOUBLE value: 'baz'
  sql.cursor().execute(stmt, params)
____
it has created 
28 table(s) | 52 rows| InnoDB | utf8_general_ci | Size 736 KiB
-- | -- | -- | -- | -- | --
____
2)trying again
 python -m Abe.abe --config abe.conf --no-serve
Opened F:\Bitcoin\blocks\blk00000.dat
Exception at 72056513014792326
Failed to catch up {'blkfile_offset': 0, 'blkfile_number': 100000, 'chain_id': None, 'loader': None, 'conf': None, 'dirname': 'F:\\Bitcoin', 'id': 2L}
Traceback (most recent call last):
  File "Abe\DataStore.py", line 2552, in catch_up
    store.catch_up_dir(dircfg)
  File "Abe\DataStore.py", line 2850, in catch_up_dir
    store.import_blkdat(dircfg, ds, blkfile['name'])
  File "Abe\DataStore.py", line 2972, in import_blkdat
    b = chain.ds_parse_block(ds)
  File "Abe\Chain\__init__.py", line 82, in ds_parse_block
    d['transactions'].append(chain.ds_parse_transaction(ds))
  File "Abe\Chain\__init__.py", line 75, in ds_parse_transaction
    return deserialize.parse_Transaction(ds)
  File "Abe\deserialize.py", line 90, in parse_Transaction
    d['txIn'].append(parse_TxIn(vds))
  File "Abe\deserialize.py", line 46, in parse_TxIn
    d['sequence'] = vds.read_uint32()
  File "Abe\BCDataStream.py", line 71, in read_uint32
    def read_uint32 (self): return self._read_num('<I')
  File "Abe\BCDataStream.py", line 110, in _read_num
    (i,) = struct.unpack_from(format, self.input, self.read_cursor)
error: unpack_from requires a buffer of at least 4 bytes
___
rows=53
now Im trying 8 times
python -m Abe.abe --config abe.conf --no-serve
___
every time I'm running it creates +1 row into table "datadir_seq", now it contains
id 1/2/3/4/5/6/7/8
____
Could you help?
