### ISSUE TITLE
IntegrityError: duplicate key value violates unique constraint "block_tx_pkey"

### ISSUE THREAD

**Issue by kirkmicz** [bitcoin-abe/bitcoin-abe#271]
Hello good day.

I have this kind of problem running dogecoin in `bitcoin-abe`. 

**DataStore.py**
```
CHAIN_CONFIG = [{"chain":"Dogecoin", "code3":"DGX", "address_version":"\x1e", "magic":"\xc0\xc0\xc0\xc0", "policy": "Sha256Chain"}]
```

**abe-pg.conf**
```
dbtype = psycopg2
connect-args = { "database": "abe" }

default-loader=rpc

port 2750
host localhost
datadir += [{
  "dirname" : "/home/ubuntu/.dogecoin",
  "conf": "/home/ubuntu/.dogecoin/dogecoin.conf",
  "chain": "Dogecoin"}]
```

both rpc and default loader throws the same error.

```
block_tx 1219095 14541265
block_tx 1219095 14541294
Failed to catch up {'blkfile_offset': 54367352, 'blkfile_number': 100035, 'chain_id': 1, 'loader': None, 'conf': u'/home/ubuntu/.dogecoin/dogecoin.conf', 'dirname': '/home/ubuntu/.dogecoin', 'id': Decimal('29510')}
Traceback (most recent call last):
  File "Abe/DataStore.py", line 2532, in catch_up
    if not store.catch_up_rpc(dircfg):
  File "Abe/DataStore.py", line 2744, in catch_up_rpc
    store.import_block(block, chain = chain)
  File "Abe/DataStore.py", line 1165, in import_block
    (block_id, tx['tx_id'], tx_pos))
  File "Abe/DataStore.py", line 233, in sql
    store._sql.sql(stmt, params)
  File "Abe/SqlAbstraction.py", line 486, in sql
    sql._execute(cached, params)
  File "Abe/SqlAbstraction.py", line 467, in _execute
    sql.cursor().execute(stmt, params)
IntegrityError: duplicate key value violates unique constraint "block_tx_pkey"
```

**Comment by kirkmicz** [comment]
In litecoin different error

```
Opened /home/ubuntu/.litecoin/blocks/blk00046.dat
Exception at 3652130237
Failed to catch up {'blkfile_offset': 29167380, 'blkfile_number': 100046, 'chain_id': 1, 'loader': None, 'conf': u'/home/ubuntu/.litecoin/litecoin.conf', 'dirname': '/home/ubuntu/.litecoin', 'id': Decimal('439')}
Traceback (most recent call last):
  File "Abe/DataStore.py", line 2530, in catch_up
    store.catch_up_dir(dircfg)
  File "Abe/DataStore.py", line 2828, in catch_up_dir
    store.import_blkdat(dircfg, ds, blkfile['name'])
  File "Abe/DataStore.py", line 2950, in import_blkdat
    b = chain.ds_parse_block(ds)
  File "Abe/Chain/__init__.py", line 82, in ds_parse_block
    d['transactions'].append(chain.ds_parse_transaction(ds))
  File "Abe/Chain/__init__.py", line 75, in ds_parse_transaction
    return deserialize.parse_Transaction(ds)
  File "Abe/deserialize.py", line 90, in parse_Transaction
    d['txIn'].append(parse_TxIn(vds))
  File "Abe/deserialize.py", line 46, in parse_TxIn
    d['sequence'] = vds.read_uint32()
  File "Abe/BCDataStream.py", line 71, in read_uint32
    def read_uint32 (self): return self._read_num('<I')
  File "Abe/BCDataStream.py", line 110, in _read_num
    (i,) = struct.unpack_from(format, self.input, self.read_cursor)
error: unpack_from requires a buffer of at least 4 bytes
```

**Comment by kirkmicz** [comment]
[aa](https://github.com/dermoth/bitcoin-abe/tree/segwit)
