### ISSUE TITLE
Migrating to Python 3

### ISSUE THREAD

**Issue by Lvl4Sword** [bitcoin-abe/bitcoin-abe#284]
Python 2 is EOL January 1st, 2020. Any plans on moving over to 3?

**Comment by ZielarSRC** [comment]
I dare doubt the interest of the main author in this project ... a pity :-(

**Comment by Lvl4Sword** [comment]
Python 2 will be EOL in 5.5 months according to python/devguide/pull/344

**Comment by dermoth** [comment]
Well then I suggest starting with the 2to3 tool - I know for a fact there will be pain points, but at least recent versions like 3.7 should alleviate some of them (ex hex encode/decode was a pita in earlier 3.x, I believe some of the 2.x behavior was re-added later on). Other recent features also make porting easier.

The original author is no longer around and I'm not only no longer using it but can't even run abe with the main Bitcoin blockchain on my home hardware anymore, so it makes things a bit hard to test.

I might give a hand if the work is lead by someone else but i'm not going to start it as I'm pretty sure I can't pull it through on my hand.

BTW there's also the segwit work that is unfinished - I have a branch that decode the newer blocks but it still lacks saving segwit to the database along with the scriptsig (when enabled).

**Comment by Lvl4Sword** [comment]
I'd love to take over development of Abe and see it through to a proper 3 port.

**Comment by Lvl4Sword** [comment]
@dermoth Would it be acceptable to have me added to the list of Bitcoin-Abe members so I can take over this project? If you're no longer using/running Abe, to me it only makes sense. This way I can get a release out before the new year.

**Comment by dermoth** [comment]
Why don't you start by submitting pr's? As long as I'm around to review and merge your code I don't see what is blocking you.

**Comment by Lvl4Sword** [comment]
```py
Traceback (most recent call last):
  File "/home/abe/abe-dir/Abe/DataStore.py", line 2562, in catch_up
    store.catch_up_dir(dircfg)
  File "/home/abe/abe-dir/Abe/DataStore.py", line 2853, in catch_up_dir
    store.import_blkdat(dircfg, ds, blkfile['name'])
  File "/home/abe/abe-dir/Abe/DataStore.py", line 2975, in import_blkdat
    b = chain.ds_parse_block(ds)
  File "/home/abe/abe-dir/Abe/Chain/__init__.py", line 80, in ds_parse_block
    nTransactions = ds.read_compact_size()
  File "/home/abe/abe-dir/Abe/BCDataStream.py", line 119, in read_compact_size
    size = ord(self.input[self.read_cursor])
TypeError: ord() expected string of length 1, but int found
```

Having:

```py
        print('self.read_cursor %s' % self.read_cursor)
        print('self.input[self.read_cursor] %s' % self.input[self.read_cursor])
        print('type(self.read_cursor) %s' % type(self.read_cursor))
        print('type(self.input[self.read_cursor]) %s' % type(self.input[self.read_cursor]))
        print('type(self.input) %s' % type(self.input))
```

in ``def read_compact_size(self):`` in BCDataStream.py`` gives me:

```py
self.read_cursor 122793104
self.input[self.read_cursor] 1
type(self.read_cursor) <class 'int'>
type(self.input[self.read_cursor]) <class 'int'>
type(self.input) <class 'mmap.mmap'>
```

whereas on a Python 2 install with:

```py
  def read_compact_size(self):
    size = ord(self.input[self.read_cursor])
    print('self.read_cursor %s' % self.read_cursor)
    print('self.input[self.read_cursor] %s' % self.input[self.read_cursor])
    print('ord(self.input[self.read_cursor]) %s' % size)
    print('type(self.read_cursor) %s' % type(self.read_cursor))
    print('type(self.input[self.read_cursor]) %s' % type(self.input[self.read_cursor]))
    print('type(ord(self.input[self.read_cursor])) %s' % type(size))
    print('type(self.input) %s' % type(self.input))
```
I get:

```py
self.read_cursor 160
self.input[self.read_cursor] ^Y
ord(self.input[self.read_cursor]) 25
type(self.read_cursor) <type 'int'>
type(self.input[self.read_cursor]) <type 'str'>
type(ord(self.input[self.read_cursor])) <type 'int'>
type(self.input) <type 'str'>
```

Current code is at https://github.com/woodcoin-core/woodcoin-explorer/tree/python3/Abe and when fully migrated over to Python 3, a PR will be available for this repo.

**Comment by Lvl4Sword** [comment]
@dermoth Any idea on the above?

**Comment by Lvl4Sword** [comment]
https://github.com/woodcoin-core/woodcoin-explorer/tree/python3 Is the Python3 version of the fork I'm maintaining.

**Comment by crabel99** [comment]
@dermoth I submitted a pull request #309 to update Abe to Python 3.

Note: This does not change the database implementation (although MySQL is known to not work and SQLite3 is untested).

@Lvl4Sword I'm going to work on transitioning this code base to Django in the New Year.

**Comment by dermoth** [comment]
Thanks, I replied on that PR.

FWIW, and I told Lvl4Sword this too, I think we should try to modularise this a bit more.

The web frontend just needs db access and a model to use to get the data it needs.

The core of the work/logic is importing data, and that could be a standalone component that receives full blocks and transactions from a chain feed

The feed could parse block files (and ideally order blocks for insert), get blocks form RPC and also for staying sync receive blocks/transactions directly from the client over its ZeroMQ interface.

This would allow different ppl to focus on a specific component, and also allow replacing completely one component without affecting anything else. For example, I could modify the loader to prepare dumps suitable for bulk-loading in a specific database, then after loading I could resume the normal loader to stay up to date - the web frontend could seep using that database during that time.

It could also permit separating the components, and we could also easily prefetch blocks ands sent them to a queue for the loader to work on, reducing the latency added by reading/parsing blocks, especially when using RPC.


Also, and I'm not sure if Lvl4Sword took that advice, the primary keys should probably be block/transaction hashes. They're bigger than current keys, especially for blocks, but they're guaranteed to be usiniw and provide two major advantages for the loading bit, which it the most problematic part for large chains:

1. You don't have to look-up any id's before linking data, you link directly with the hashes
2. Foreign keys can be disabled for load, and creating dumps for bulk-loading is very easy.

This would reduce significantly the read IO and lower insert latency, and allow for blazing fast bulk imports.

OTOH this will lead to larger tables, and that difference may depend on the actual database engine; for instance I know InnoDB copies the PK for every secondary key, so a tables with many keys could be significantly affected.
