### ISSUE TITLE
OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by WesNz** [bitcoin-abe/bitcoin-abe#290]
Been syncing the chain for quite some time.... then now i get this error below..
not sure why and have zero clue.

Using mysql if that helps?

abe@abe:~/bitcoin-abe$ python -m Abe.abe --config abe-my.conf --commit-bytes 100000 --no-serve
no chain_id
catch_up_rpc: abort
Opened /home/abe/.bitcoin/blocks/blk00979.dat
Exception at 12096905734139984649
Failed to catch up {'blkfile_offset': 90216123, 'blkfile_number': 100979, 'chain_id': None, 'loader': None, 'dirname': '/home/abe/.bitcoin', 'id': Decimal('1')}
Traceback (most recent call last):
  File "Abe/DataStore.py", line 2563, in catch_up
    store.catch_up_dir(dircfg)
  File "Abe/DataStore.py", line 2855, in catch_up_dir
    store.import_blkdat(dircfg, ds, blkfile['name'])
  File "Abe/DataStore.py", line 2977, in import_blkdat
    b = chain.ds_parse_block(ds)
  File "Abe/Chain/__init__.py", line 82, in ds_parse_block
    d['transactions'].append(chain.ds_parse_transaction(ds))
  File "Abe/Chain/__init__.py", line 75, in ds_parse_transaction
    return deserialize.parse_Transaction(ds)
  File "Abe/deserialize.py", line 90, in parse_Transaction
    d['txIn'].append(parse_TxIn(vds))
  File "Abe/deserialize.py", line 46, in parse_TxIn
    d['sequence'] = vds.read_uint32()
  File "Abe/BCDataStream.py", line 71, in read_uint32
    def read_uint32 (self): return self._read_num('<I')
  File "Abe/BCDataStream.py", line 110, in _read_num
    (i,) = struct.unpack_from(format, self.input, self.read_cursor)
OverflowError: Python int too large to convert to C long
abe@abe:~/bitcoin-abe$

**Comment by dermoth** [comment]
This looks like there may be some corruption in your blockchain... Can you try with the RPC loader? Ii it still fails check for possible errors in you bitcoin node logs too.
