### ISSUE TITLE
Failed to catch up error - OverflowError

### ISSUE THREAD

**Issue by toonboifresh** [bitcoin-abe/bitcoin-abe#303]
Hi all

I've been trying to get an instance of Abe up and running but have run into a bit of a snag.  I couldn't find a solution that worked for this, so decided to post here.  Hoping someone can help me out.  I am running MySQL 5.7.33 and everything seems to be OK on that side.  Abe is configured as below, and the data directory is working and reading bitcoin blk*****.dat files seems to be fine (at the start).

```
dbtype MySQLdb
connect-args {"user":"abe1","db":"abe"}
upgrade
port 2750
```

I let it run on initial startup and everything seemed to be working as expected but I quickly ran into an error.  The snippet below is from trying to force a rescan, but the error itself is the same.

executed using: python -m Abe.abe --config abe.conf --commit-bytes 10000 --no-serve --rescan

```
block 4175 already in chain 1
block 4176 already in chain 1
Exception at 969746
Failed to catch up {'blkfile_offset': 968753, 'blkfile_number': 100000, 'chain_id': 1, 'loader': u'blkfile', 'conf': None, 'dirname': 'G:/Users/****/Downloads/Bitcoin Database/Bitcoin', 'id': Decimal('1')}
Traceback (most recent call last):
  File "Abe\DataStore.py", line 2557, in catch_up
    store.catch_up_dir(dircfg)
  File "Abe\DataStore.py", line 2855, in catch_up_dir
    store.import_blkdat(dircfg, ds, blkfile['name'])
  File "Abe\DataStore.py", line 2977, in import_blkdat
    b = chain.ds_parse_block(ds)
  File "Abe\Chain\__init__.py", line 81, in ds_parse_block
    for i in xrange(nTransactions):
OverflowError: Python int too large to convert to C long
```

I found this in the config, but it doesn't seem to do anything for this.  

```
# Some databases have trouble with the large integers that Abe uses
# for statistics.  Setting int-type=str causes Abe to pass certain
# integers to the database as strings and cast them to floating point
# in SQL expressions that calculate statistics.  Try this if SQLite
# complains "OverflowError: long too big to convert".

int-type=str
int-type str
```

I've already tried deleting the database and rebuilding it, no luck.  I've also made sure I'm running 64bit python and not 32bit - heard there were issues with int lengths on 32bit python.  OS = Win 10

Any ideas on how to get this up and running?

Thanks in advance

**Comment by dermoth** [comment]
Hi,

Most likely you are using a 32bit version of python and/or mysql. Make sure you use 64 bit version that support 64bit integers natively. AFAIK the str type was a fix for SQLIte databases that had deficiencies and are likely not a good idea.

That said, please be aware that Abe hasn't been maintained much lately. The current master doesn't support segwit and will stop at block 481824. I partially implemented setwit in my fork's segwit branch, however it's limited to decoding and throws away the segwit data (irrelevant if you have `keep-scriptsig false`) and loses the tx weigth. On top of that python 2.7 is no longer supported and a port to 3.x is unlikely (pretty complex). There are also some suspected issues that cause database corruption (most evident sign is many stats becoming all 0's at one point)

A rewrite is being worked on by a community member, however it still in its early stages... expect an official announcement soon. 

If you insist on using Abe you should at least use the RPC loader as recent Bitcoind versions save blocks in random order and this may cause issues (the rpc loader is also much faster than is used to be). Make sure you uses latest Abe from master branch, and merge in my fork's segwit branch if you will be loading segwit blocks. Make db backups often and watch for stats issues that would require rolling back to an earlier snapshot.

Also keep in mind while early blocks load fast it goes much slower as number of tx per block increases. Unless you can fit the whole dataset in ram an SSD is probably a minimum requirement for the database as each block/tx/tx input trigger several FK checks on inserts.

Regards
