### ISSUE TITLE
Connect to an external MySQL with tcp/ip

### ISSUE THREAD

**Issue by medisoft** [bitcoin-abe/bitcoin-abe#32]
Hi! I want to know the connect-args settings to connect abe to an external mysql server.

At the moment I tested adding "host" and "server" but I think I'm wrong in the parameter name.

If it is not possible at the moment, I want to ask for that support :)

Thanks.

**Comment by AkiraTakizawa** [comment]
Until now I worked with a local mysqldb, but having migrated to a new server, I can use an offloaded MySQL db. I created a user and database and can connect to it, using the mysql command.

When I try to start bitcoin-abe for the initial load, I get **local** mysql server errors?

```
Reconnecting after rollback error: (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")
Reconnecting to database.
Reconnecting after rollback error: (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")
Reconnecting to database.
Reconnecting after rollback error: (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")
Reconnecting to database.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/Abe/abe.py", line 2101, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/lib/python2.7/dist-packages/Abe/abe.py", line 2095, in main
    store = make_store(args)
  File "/usr/local/lib/python2.7/dist-packages/Abe/abe.py", line 159, in make_store
    store = DataStore.new(args)
  File "/usr/local/lib/python2.7/dist-packages/Abe/DataStore.py", line 3277, in new
    return DataStore(args)
  File "/usr/local/lib/python2.7/dist-packages/Abe/DataStore.py", line 187, in __init__
    store.initialize()
  File "/usr/local/lib/python2.7/dist-packages/Abe/DataStore.py", line 629, in initialize
    store.configure()
  File "/usr/local/lib/python2.7/dist-packages/Abe/DataStore.py", line 927, in configure
    config = store._sql.configure()
  File "/usr/local/lib/python2.7/dist-packages/Abe/SqlAbstraction.py", line 614, in configure
    sql.configure_ddl_implicit_commit()
  File "/usr/local/lib/python2.7/dist-packages/Abe/SqlAbstraction.py", line 699, in configure_ddl_implicit_commit
    if sql._test_ddl():
  File "/usr/local/lib/python2.7/dist-packages/Abe/SqlAbstraction.py", line 706, in _test_ddl
    sql.drop_table_if_exists("%stest_1" % sql.prefix)
  File "/usr/local/lib/python2.7/dist-packages/Abe/SqlAbstraction.py", line 677, in drop_table_if_exists
    sql._drop_if_exists("TABLE", obj)
  File "/usr/local/lib/python2.7/dist-packages/Abe/SqlAbstraction.py", line 674, in _drop_if_exists
    sql.rollback()
  File "/usr/local/lib/python2.7/dist-packages/Abe/SqlAbstraction.py", line 603, in rollback
    sql.reconnect()
  File "/usr/local/lib/python2.7/dist-packages/Abe/SqlAbstraction.py", line 292, in reconnect
    return sql.conn()
  File "/usr/local/lib/python2.7/dist-packages/Abe/SqlAbstraction.py", line 275, in conn
    sql._conn = sql.connect()
  File "/usr/local/lib/python2.7/dist-packages/Abe/SqlAbstraction.py", line 233, in connect
    conn = sql.module.connect()
  File "/usr/lib/python2.7/dist-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 187, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.OperationalError: (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")
```

The DB is configured as:
```
dbtype MySQLdb
connect-­args {"user":"mine1_akira","db":"mine1_abe","passwd":"mypassword","host":"192.211.56.74","port":3306}
```

**Comment by Spekske** [comment]
Did you configure the remote host running the MySQL DB to allow access from the machine running Abe ?

**Comment by AkiraTakizawa** [comment]
Thanks for replying Spekske. 
The remote DB server accepts connections from the host running Abe. I am confused about Abe wanting to connect to a local DB: ```"Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)"```
This file and directory do not exist as I did not install the mysql-server package, having a high performance external DB server to handle all the queries.

**Comment by Spekske** [comment]
You might want to check this:
https://dev.mysql.com/doc/refman/5.0/en/can-not-connect-to-server.html

**Comment by AkiraTakizawa** [comment]
From what I understand UNIX sockets are only used when no host IP is specified or when "localhost" is given as the host. When an IP address is specified, mysql should connect using TCP. This is what should happen, as I need it to connect to 192.211.56.74.
