### ISSUE TITLE
Block header Merkle root does not match its transactions

### ISSUE THREAD

**Issue by csyangchen** [bitcoin-abe/bitcoin-abe#77]
it seems that Verify Merkle root procedure is broken somehow:

MerkleRootMismatch: Block header Merkle root does not match its transactions. block hash=00000000594fd07b9f9e7dea58f56d227de5d829f47863ffafdc593f73a4851e

**Comment by davidmanheim** [comment]
I'm having the same problem, at the same point, on the bitcoin blockchain.
Per @Spekske's idea, I removed the check from the DataStore.py, and it runs - but I'd prefer if this were fixed instead.

**Comment by dermoth** [comment]
What version of Abe exactly (release or commit hash)? I never seen that error; running on the latest head from master branch.

**Comment by davidmanheim** [comment]
I installed from branch "Master" as of when I sent that message, so commit 16acafe, the same as you ran.

**Comment by dermoth** [comment]
What block is it failing on? Can you paste the stack trace, block # if you have it and last block imported? (you can see it from web interface when starting with --no-load)

I just looked at jtobey's response above, it does look like filesystem corruption which isn't unheard of on consumer hardware. Are you able to check the block/merkle tree hashes and compare them from blockchain.info (you'll have to get them from bitcoind for the specific block it's failing on, or using file/offset and decode the block). 

I suggest re-importing the blocks in bitcoind from scratch... I don't think you'll have to clear entirely abe's database, at worst clearing the block (which I don't even think will be there) and related tx's should do (if you run the latest version tx'es will actually be unlinked if there at all; check the unlinked_tx table - clearing them requires multiple steps, see commit 16acafe). I can provide the commands to clear tx'es, or even better an admin tool to do it . If you disabled the check and kept importing though you would have to clean a lot more data...

Maybe check with bitcoin developers whenever there's a way to check all blocks or re-import a specific block too, that would save a lot of time.

**Comment by vibhcool** [comment]
I am loading bitcoin in abe, And I have got MerkleRootMismatch error:

```
no chain_id
catch_up_rpc: abort
Opened /home/raptor/.bitcoin/blocks/blk00975.dat
Exception at 131522649
Failed to catch up {'blkfile_offset': 131522541, 'blkfile_number': 100975, 'chain_id': None, 'loader': None, 'dirname': '/home/raptor/.bitcoin', 'id': Decimal('1')}
Traceback (most recent call last):
  File "Abe/DataStore.py", line 2563, in catch_up
    store.catch_up_dir(dircfg)
  File "Abe/DataStore.py", line 2843, in catch_up_dir
    store.import_blkdat(dircfg, ds, blkfile['name'])
  File "Abe/DataStore.py", line 2975, in import_blkdat
    store.import_block(b, chain = chain)
  File "Abe/DataStore.py", line 1091, in import_block
    raise MerkleRootMismatch(b['hash'], tx_hash_array)
MerkleRootMismatch: Block header Merkle root does not match its transactions. block hash=000000000000000000bc331eb461d522cb3673b3881217dc30c6a5cf91710f23

```

**Comment by marioschlipf** [comment]
Probably not working because of segwit, try my fork:
https://github.com/marioschlipf/bitcoin-abe

**Comment by dermoth** [comment]
You may want to look at my work too - I've also implemented some tests...

https://github.com/dermoth/bitcoin-abe/commits/segwit

**Comment by dermoth** [comment]
It's mentioned on the segwit-related issues, and this one has nothing to do with segwit. De-serialization works, but when Abe is configured to save scriptsig then witness should be saved as well and it's lacking it for now. I'd like to have at least the back-end properly implemented otherwise it will require re-importing all segwit blocks anyway.

Unfortunately I no longer have a sufficiently fast system for that... would need at least an SSD large enough for the data tables (and bitcoind ideally)... And even if I had one consumer-grade I'd probably wouldn't waste it on Abe's IO... Write life is limited and it's the primary reason I moved away form my SSD before size was even an issue.
