### ISSUE TITLE
Issues once Abe "caught up"

### ISSUE THREAD

**Issue by njmurarka** [bitcoin-abe/bitcoin-abe#82]
Abe was running just fine for about the 8 weeks it took on my server (which could be considered slow given the 8 weeks). I was monitoring it and the latest block it was processing was steadily going up. I am using MySQL.

Once it was all "caught up", it was no longer behaving. I am afraid to mess around with the server much in case I lose the 8 weeks of work it took to get it here.

Below is a dump of what happens when I try to connect to the local server at port 2750. The page came up on the web browser, but it seems the web server died and the abe script has had to restart or something again. Also, it seems the abe server/script is no longer keeping up with new blocks. It is at least a week behind now so maybe the way I am running it now is different and it is not even taking in the latest blocks coming in on the blockchain? I verified that the local bitcoind is running fine and has the latest blocks. 

The block_height column value in the block table has been NULL ever since Abe caught up.

commit
incomplete block of length 374569 chain 1
Abe initialized.
Listening on http://localhost:2750
no chain_id
catch_up_rpc: abort
Failed to catch up {'blkfile_offset': 100438231, 'blkfile_number': 100122, 'chain_id': None, 'loader': None, 'dirname': '/root/.bitcoin', 'id': Decimal('1')}
Traceback (most recent call last):
  File "Abe/DataStore.py", line 2639, in catch_up
    store.catch_up_dir(dircfg)
  File "Abe/DataStore.py", line 2886, in catch_up_dir
    blkfile = open_blkfile(dircfg['blkfile_number'])
  File "Abe/DataStore.py", line 2840, in open_blkfile
    store._refresh_dircfg(dircfg)
  File "Abe/DataStore.py", line 3095, in _refresh_dircfg
    WHERE dirname = ?""", (dircfg['dirname'],))
  File "Abe/DataStore.py", line 638, in selectrow
    store.sql(stmt, params)
  File "Abe/DataStore.py", line 510, in sql
    store._execute(cached, params)
  File "Abe/DataStore.py", line 487, in _execute
    store.cursor.execute(stmt, params)
  File "/usr/lib/pymodules/python2.6/MySQLdb/cursors.py", line 166, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/pymodules/python2.6/MySQLdb/connections.py", line 35, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (2006, 'MySQL server has gone away')
Reconnecting after rollback error: (2006, 'MySQL server has gone away')
Reconnecting to database.
localhost.localdomain - - [19/Mar/2014 03:37:00] "GET / HTTP/1.0" 200 1544
no chain_id
catch_up_rpc: abort
Opened /root/.bitcoin/blocks/blk00122.dat

**Comment by coinflow** [comment]
I don't know whether it is the same cause, but I had the same problem with Abe being stuck, only after it run fine for a few weeks. When doing a rescan, it threw a message of "double transcation" or so and quit. So the whole database had to be rebuilt or had to use a database-backupfile (MariaDB, but previously MySQL with the same problem), to at least have the last working state to build on and not loading the whole database from scratch again.

Since I'd like to understand what is happening and avoiding this in the future: Could this have to do with multiple instances of Abe running at the same time concurrently, which are inserting the same tx, hence creating an inconsistency, that keeps it later to catch up correctly?  The [script](https://github.com/bitcoin-abe/bitcoin-abe/blob/master/tools/abe_loader) is used. Maybe that collides with Abe starting again and again, when the web-frontend is visited? How does the Abe/Python/MySQL-combination handle this?

Any ideas what could be the problem, if this is not the cause?

**Comment by coinflow** [comment]
Another thought in this regard: Can we use blocknotify like described by John Tobey here: https://bitcointalk.org/index.php?topic=22785.msg2735683#msg2735683
The same question arises, what happens, if the *coind notifies Abe with a new block, when the old one is not even fully written into the database, which can happen for coins with short blocktime like 1 or two minutes and many transactions in them.

**Comment by dermoth** [comment]
First please try to separate the loader from web server. I haven't run a single loader/server process for a long time and I'm unsure if it will work well, especially with the RPC loader which you appear to be using.

I don't think single loader/webserver should be supported anymore, since parallel import is not supported meaning that:

1. You can only serve a single web request at once. Somebody asking for a full block's transaction list? Too bad, other quick queries like getting current height will have to wait!
2. If a new block need to be imported, it will have to be fully imported before the next request is server. Again, everyone will have to wait until the block is imported!
3. If you attempt to run multiple processes, they will all try importing the same data at once!

So please run the importer once with:

    python -m Abe.abe --config myconf.conf --no-serve --rpc-load-mempool=false

Then try running the web server and fetching data with:

    python -m Abe.abe --config myconf.conf --no-load

Report any error encountered.

Also, can you confirm the database backend used? If you use a transaction-safe DB such as InnoDB it's very unlikely that the data gets corrupted even if you accidentally run multiple import processes at once.
